#!/usr/bin/env node
// Record the DuckDB SQL oracle: run every case in cases.json through the
// NATIVE duckdb CLI and write recorded/results.json. The replay lane is
// packages/data-bundle/test/duckdb-sql-oracle.spec.ts. See
// docs/design/oracles.md.
//
//   DUCKDB=/path/to/duckdb node conformance/duckdb-sql/record.mjs
//
// The CLI must be the SAME engine version as the one inside the shipped
// duckdb-wasm (cases.json `engine`; v1.1.1 for @duckdb/duckdb-wasm 1.29.0).
// Releases: https://github.com/duckdb/duckdb/releases/tag/v1.1.1
// (duckdb_cli-osx-universal.zip). A different version is refused, because
// CSV sniffing and type rules move between releases.
//
// Values are recorded LOSSLESSLY as DuckDB's own VARCHAR cast of each cell
// (null stays null), with the column types from DESCRIBE. The replay lane
// derives the expected RecordSet cell from (type, text) by the data-core
// contract (Date = days, DateTime = ms UTC, numbers = f64).
import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DUCKDB = process.env.DUCKDB ?? "duckdb";
const cases = JSON.parse(readFileSync(join(HERE, "cases.json"), "utf8"));

function run(db, sql) {
  const out = execFileSync(DUCKDB, ["-json", db, "-c", sql], { encoding: "utf8" }).trim();
  return out ? JSON.parse(out) : [];
}

const tmp = mkdtempSync(join(process.env.TMPDIR ?? tmpdir(), "duckdb-oracle-"));
const db = join(tmp, "oracle.duckdb");
try {
  const version = run(db, "SELECT version() AS v, (SELECT source_id FROM pragma_version()) AS s")[0];
  if (version.v !== cases.engine) {
    throw new Error(`duckdb CLI is ${version.v}; the shipped duckdb-wasm engine is ${cases.engine}`);
  }

  // Register every CSV as a table, the way registerCsv does in the bundle
  // (insertCSVFromPath with detect → read_csv auto-detection).
  const csvDir = join(HERE, "csv");
  const tables = {};
  for (const file of readdirSync(csvDir).filter((f) => f.endsWith(".csv")).sort()) {
    const name = basename(file, ".csv");
    run(db, `CREATE TABLE "${name}" AS SELECT * FROM read_csv_auto('${join(csvDir, file)}')`);
    tables[name] = run(db, `DESCRIBE "${name}"`).map((c) => ({ name: c.column_name, type: c.column_type }));
  }

  const results = [];
  for (const c of cases.cases) {
    const columns = run(db, `DESCRIBE ${c.sql}`).map((d) => ({ name: d.column_name, type: d.column_type }));
    const cells = columns.map((col) => `CAST("${col.name.replaceAll('"', '""')}" AS VARCHAR)`).join(", ");
    const rows = run(db, `SELECT json_array(${cells})::VARCHAR AS r FROM (${c.sql}) AS q`).map((r) =>
      JSON.parse(r.r),
    );
    results.push({ id: c.id, sql: c.sql, columns, rows });
  }

  const out = {
    $comment: "GENERATED by conformance/duckdb-sql/record.mjs from the native duckdb CLI — do not edit by hand.",
    engine: { version: version.v, source_id: version.s },
    tables,
    results,
  };
  writeFileSync(join(HERE, "recorded", "results.json"), JSON.stringify(out, null, 2) + "\n");
  console.log(`recorded ${results.length} cases with duckdb ${version.v} (${version.s})`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
