/*
 * This file is part of paged (https://paged.media).
 *
 * paged is free software: you may redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License, version 3, as published by
 * the Free Software Foundation, OR under the Paged Media Enterprise License
 * (PMEL), a commercial license available from And The Next GmbH. Full
 * copyright and license information is available in LICENSE.md, distributed
 * with this source code.
 *
 * paged is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the licenses for details.
 *
 *  @copyright  Copyright (c) And The Next GmbH
 *  @license    AGPL-3.0-only OR Paged Media Enterprise License (PMEL)
 */

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * This file is part of paged (https://paged.media) and is additionally
 * available under the Paged Media Enterprise License (PMEL). Full
 * copyright and license information is available in LICENSE.md which is
 * distributed with this source code.
 *
 *  @copyright  Copyright (c) And The Next GmbH
 *  @license    MPL-2.0 OR Paged Media Enterprise License (PMEL)
 */

//! # data-core — the frozen paged.data type contract
//!
//! The leaf crate of the paged.data engine (spec §5): the stored [`Value`],
//! the [`ids`], the source/query/record model ([`model`]), the [`binding`] +
//! placeholder + sync types, and the dialect-neutral expression [`expr`] AST.
//! It depends on nothing in the workspace — every other `data-*` crate depends
//! on it.
//!
//! ## FROZEN at M0 phase 0 (interface freeze)
//!
//! These types, the AST, and the registry YAML schema are **frozen**. Changes
//! go through the orchestrator as **versioned amendments**, never drive-by
//! edits (repo constitution, CLAUDE.md §"Interface freeze"). The expression
//! function table is **registry-driven**: it is generated at build time from
//! `registry/functions/*.yaml` (`build.rs`), so an unregistered function has no
//! [`expr::FnId`] and is uncallable by construction.

pub mod binding;
pub mod expr;
pub mod ids;
pub mod model;
pub mod temporal;
pub mod value;

/// The registry-generated expression-function table (name → [`expr::FnId`],
/// metadata). Generated by `build.rs` from `../registry/functions/*.yaml`.
pub mod funcs {
    include!(concat!(env!("OUT_DIR"), "/funcs.rs"));
}

pub use binding::{
    BarcodeMissing, BarcodeOpts, BarcodeSymbology, Binding, BindingDef, ColumnBind, FlowOpts,
    FooterAgg, GroupFooter, ImageReference, ImageStatus, ImgFit, ImgMissing, ImgPolicy,
    MissingPolicy, Placeholder, PlaceholderKind, ResolveStamp, Status, StyleAction, SyncState,
    TableOpts, Template, TemplateField,
};
pub use expr::{BinOp, Expr, FnId, UnaryOp};
pub use ids::{
    BindingId, CapabilityRef, FrameChainRef, FrameRef, PlaceholderRef, QueryId, ScopeRef, SourceId,
    TemplateRef,
};
pub use model::{
    DataSource, DbEngine, Field, FieldType, FileFormat, Locale, ParamDecl, ParamType, Query,
    RecordError, RecordSet, RefreshPolicy, ResultShape, Schema, SourceKind,
};
pub use value::{Value, ValueError};
